version: '3.7'

networks:
    services:
      ipam:
        config:
          - subnet: 10.0.0.0/8

services:
    ledger:
        build:
            context: ./distributed-ledger
            args:
                - pool_ip=10.0.0.2
        restart: always
        ports:
            - "9701-9708:9701-9708"
        networks:
            services:
                ipv4_address: 10.0.0.2

    api:
        build: ./api-server
        environment:
            - TEST_POOL_IP=10.0.0.2
            - DATABASE_HOST=db
        depends_on:
            - ledger
        restart: always
        ports:
            - "9000:9000"
        networks:
            services:
                ipv4_address: 10.0.0.3